PasswordAuthentication no
KbdInteractiveAuthentication no
PermitRootLogin no
PubkeyAuthentication yes
AllowTcpForwarding yes
AllowAgentForwarding yes
StrictModes no
PidFile /tmp/sshd.pid
HostKey /home/.ssh/ssh_host_ed25519_key
AuthorizedKeysFile /home/.ssh/authorized_keys
